###################################################################
# (c) Copyright 2008 Wi-Fi Alliance.  All Rights Reserved
#
# Authors:
# Qiumin Hu;       Email: qhu@wi-fi.org
# Ankur Vachhani;  Email: avachhani@wi-fi.org
####################################################################
# LICENSE
####################################################################
#
#
# License is granted only to Wi-Fi Alliance members and is for use solely
# in testing Wi-Fi products. This license is not transferable or sublicensable,
# and it does not extend to and may not be used with non Wi-Fi applications.
#
# Commercial derivative works or applications that use the Wi-Fi
# scripts generated by this software are NOT AUTHORIZED without
# specific prior written permission from Wi-Fi Alliance
#
# Non-commercial derivative works for your own internal use are
# authorized and are limited by the same restrictions.
#
# Neither the name of the author nor "Wi-Fi Alliance"
# may be used to endorse or promote products that are derived
# from or that use this software without specific prior written
# permission from the author or Wi-Fi Alliance
#
# THIS SOFTWARE IS PROVIDED BY WI-FI ALLIANCE "AS IS" AND ANY
# EXPRESSED OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY, NON-INFRINGEMENT AND FITNESS
# FOR A  PARTICULAR PURPOSE, ARE DISCLAIMED. IN NO EVENT SHALL WI-FI
# ALLIANCE BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
# EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# THE COST OF PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
###################################################################
# Change History
#       Date        Version          Comment 
#       12/5/2007    0.1             Initial Prototype release for WMM
#        
###################################################################
#


#!/usr/bin/evn python
import os, sys
from myutils import scanner
from myutils import process_ipadd
from myutils import process_cmdfile
from myutils import firstword
from myutils import init_logging
from myutils import printStreamResults 
from myutils import close_conn
from myutils import wfa_sys_exit
from myutils import setUCCPath
from myutils import reset
from InitTestEnv import InitTestEnv
import logging
import time
import re
nargs = len(sys.argv)

class UCCTestConfig:
    
    def __init_(self,testID,cmdPath,progName,initFile,TBFile):
        self.cmdPath=cmdPath
        self.progName=progName
        self.initFile=initFile
        self.TBFile=TBFile
        self.testID=testID
      
  
    def __str__(self):
        return("\n Test ID = [%s] CmdPath = [%s] Prog Name = [%s] initFile =[%s] TBFile =[%s]" % (self.testID,self.cmdPath,self.progName,self.initFile,self.TBFile))

U = UCCTestConfig()

def main():

    if (nargs < 3) or (sys.argv[2]=='group' and nargs < 4):
        print('Incorrect Command line !!! \n\rUSAGE : UCC <Program Name> <Test ID>/\
        \n\r    [1]Program Name :PMF\
        \n\r                     P2P\
        \n\r                     N\
        \n\r                     WPA2\
        \n\r                     WMM-B/WMM-BG/WMM-ABG\
	\n\r\n\r [2] Test ID : Test case ID for that program            OR\
	\n\r\n\r [2] group : group if running group of test cases followed by group file name\
	\n\r\n\r [3] group file name: Group file name which contains list of test cases\
        \n\r\n\r\
        \n\r        For example, To run test P2P-4.1.1 of P2P(Wi-Fi Direct) program,\
        \n\r\n\r    UCC P2P P2P-4.1.1        OR\
        \n\r        For example, To run group of P2P test cases listed in file L1.txt\
        \n\r\n\r    UCC P2P group L1.txt\
    	')
	return


    cmdPath = ReadMapFile("Sigma-UCC.txt","%s_CMD_PATH" %(sys.argv[1]),"=")
    tbAP = ReadMapFile("Sigma-UCC.txt","%s_TESTBED_AP" %(sys.argv[1]),"=")
    tests= ReadMapFile("Sigma-UCC.txt","%s_TEST_LIST" %(sys.argv[1]),"=")
    
    if cmdPath == -1 or tbAP == -1 or tests == -1:
        print "Invalid Program Name - %s" % sys.argv[1]
        return
    setattr(U,"cmdPath",cmdPath)
    setattr(U,"progName",sys.argv[1])
    setattr(U,"TBFile",tbAP)
    
    grp = 0
    
    if sys.argv[2] == "group":
        grpFile = sys.argv[3]
        if os.path.exists(grpFile) == 0:
            print ("Invalid Group File -%s-" % grpFile)
            return
        fileP = open(grpFile,'r')
        for l in (fileP.readlines()):
            if not l: break
            setattr(U,"testID",l.strip())
            runTestCase(tests,U.testID,grp)
            grp=1
    
    else:
        setattr(U,"testID",sys.argv[2])
        runTestCase(tests,U.testID)
    
    return

def runTestCase (testListFile, testID,grp=0):
    print "\n*** Running Test - %s *** \n" % testID
    
    initFile = ReadMapFile(testListFile,testID,"!")
    testFile = ReadMapFile(testListFile,testID,"!",2)
        
    if initFile == -1 or testFile == -1:
        print ("Invalid test case - %s" % testID)
        
    setattr(U,"initFile",initFile)

    #init Logging
    init_logging(U.testID,1,grp)

    logging.info("\n Test Info %s" % U)


    uccPath=U.cmdPath
    if (uccPath.endswith('\\') == 0 ):
        uccPath=uccPath + '\\'

    setUCCPath(uccPath)
    initFile = uccPath + initFile
    testFile= uccPath + testFile
    # Run Init Env
    if not re.search("WMM",testID):
        InitTestEnv(U.testID,U.cmdPath,U.progName,U.initFile,U.TBFile)

    # UCC 
    #Run UCC Core
    
    if os.path.exists(initFile) == 0:
        logging.error ("Invalid file name - %s" % initFile)
        wfa_sys_exit("1")
   
    
    if os.path.exists(testFile) == 0:
        logging.error ("Invalid file name - %s" % cmd)
        wfa_sys_exit("1")
        
    logging.info("\n %7s Testcase Init File = %s \n" %( "",initFile))
    logging.info("\n %7s Testcase Command File = %s \n" % ("",testFile))

    logging.info ("START: TEST CASE [%s] " % testID)
    try:  
        file = open(initFile)
        scanner(file, firstword)
        process_cmdfile(testFile)
    except StandardError:
        logging.info ("END: TEST CASE [%s] " % testID)
        reset()
        return
    
    
    #delay for last receive_stop response
    time.sleep(5)
    printStreamResults()
    file.close()
    close_conn()
    time.sleep(2)

def ReadMapFile (filename,index,delim,n=1):

    iCount=1
    returnString=-1
    if os.path.exists(filename) == 0:
        print ("File not found -%s-" % filename)
        return -1
    #print ("ReadMapFile ------- %s-%s-%s" %(filename,index,delim))
    fileP = open(filename,'r')
    for l in (fileP.readlines()):
        if not l: break
        line=l.split('#')
        command = line[0].split(delim)
        #print ("ReadMapFile ------- %s" %(command))
        if index in command:
            returnString=command[command.index(index)+n].strip()
            break

    fileP.close()   
    return returnString



if __name__ == "__main__":
    main()
